// Generated by CoffeeScript 1.8.0
var Post;

Post = require('../models/post');

module.exports = {
  index: function(req, res) {
    return Post.find({}, function(err, posts) {
      return res.render('posts/index', {
        posts: posts
      });
    });
  }
};
